name: test
version: 1.0
main: com.calcite.Main
api-version: '1.21'
commands:
  start:
    usage: /start
  placepowerup:
    usage: /placepowerup
  removepowerup:
    usage: /removepowerup
  endgame:
    usage: /endgame
#  testcommand:
#    usage: /testcommand